import allure
import pytest
import time

from schemas.link_schema import LINK_SCHEMA
from utils.assertions import (
    assert_status_code,
    assert_json_has_keys,
    assert_schema
)


pytestmark = pytest.mark.lifecycle


def get_trash_path_by_name(client, resource_name, attempts=10, delay=1):
    for _ in range(attempts):
        trash_response = client.get_trash_resource_metadata(
            path="/",
            limit=1000
        )
        trash_body = trash_response.json()

        assert_status_code(trash_response, 200)

        for item in trash_body["_embedded"]["items"]:
            if item["name"] == resource_name:
                return item["path"].replace("trash:", "")

        time.sleep(delay)

    raise AssertionError(f"Resource '{resource_name}' not found in trash")


@allure.feature("Trash lifecycle")
@allure.story("Restore resource from trash")
@allure.title("Should restore deleted folder from trash")
def test_restore_folder_from_trash(client, unique_folder_name, created_folders):
    with allure.step("Create folder"):
        create_response = client.create_folder(unique_folder_name)
        assert_status_code(create_response, 201)

    with allure.step("Move folder to trash"):
        delete_response = client.delete_resource(
            path=unique_folder_name,
            permanently=False
        )
        assert_status_code(delete_response, 204)

    with allure.step("Get real folder path in trash"):
        trash_path = get_trash_path_by_name(client, unique_folder_name)

    with allure.step("Restore folder from trash"):
        restore_response = client.restore_from_trash(path=trash_path)
        body = restore_response.json()
        created_folders.append(unique_folder_name)

    with allure.step("Validate restore response"):
        assert restore_response.status_code in [201, 202]
        assert_schema(body, LINK_SCHEMA)
        assert body["method"] == "GET"
        assert body["templated"] is False

    with allure.step("Validate restored folder metadata"):
        metadata_response = client.get_resource_metadata(unique_folder_name)
        metadata_body = metadata_response.json()

        assert_status_code(metadata_response, 200)
        assert metadata_body["name"] == unique_folder_name
        assert metadata_body["type"] == "dir"
        assert metadata_body["path"] == f"disk:/{unique_folder_name}"


@allure.feature("Trash lifecycle")
@allure.story("Restore resource from trash")
@allure.title("Should restore deleted folder with new name")
def test_restore_folder_from_trash_with_new_name(client, unique_folder_name, created_folders):
    restored_name = f"{unique_folder_name}_restored"

    with allure.step("Create folder"):
        create_response = client.create_folder(unique_folder_name)
        assert_status_code(create_response, 201)

    with allure.step("Move folder to trash"):
        delete_response = client.delete_resource(
            path=unique_folder_name,
            permanently=False
        )
        assert_status_code(delete_response, 204)

    with allure.step("Get real folder path in trash"):
        trash_path = get_trash_path_by_name(client, unique_folder_name)

    with allure.step("Restore folder from trash with new name"):
        restore_response = client.restore_from_trash(
            path=trash_path,
            name=restored_name
        )
        body = restore_response.json()
        created_folders.append(restored_name)

    with allure.step("Validate restore response"):
        assert restore_response.status_code in [201, 202]
        assert_schema(body, LINK_SCHEMA)

    with allure.step("Validate restored folder metadata"):
        metadata_response = client.get_resource_metadata(restored_name)
        metadata_body = metadata_response.json()

        assert_status_code(metadata_response, 200)
        assert metadata_body["name"] == restored_name
        assert metadata_body["type"] == "dir"
        assert metadata_body["path"] == f"disk:/{restored_name}"


@allure.feature("Trash lifecycle")
@allure.story("Restore resource from trash")
@allure.title("Should restore folder with autogenerated name when target already exists")
def test_restore_folder_from_trash_without_overwrite_to_existing_path(
        client,
        unique_folder_name,
        created_folders
):
    with allure.step("Create source folder"):
        create_response = client.create_folder(unique_folder_name)
        assert_status_code(create_response, 201)

    with allure.step("Move source folder to trash"):
        delete_response = client.delete_resource(
            path=unique_folder_name,
            permanently=False
        )
        assert_status_code(delete_response, 204)

    with allure.step("Get real folder path in trash"):
        trash_path = get_trash_path_by_name(client, unique_folder_name)

    with allure.step("Create folder with same name on disk"):
        create_same_name_response = client.create_folder(unique_folder_name)
        created_folders.append(unique_folder_name)
        assert_status_code(create_same_name_response, 201)

    with allure.step("Restore without overwrite"):
        restore_response = client.restore_from_trash(
            path=trash_path,
            overwrite=False
        )
        body = restore_response.json()

    with allure.step("Validate restore response"):
        assert_status_code(restore_response, 201)
        assert_schema(body, LINK_SCHEMA)

        assert body["method"] == "GET"
        assert body["templated"] is False
        assert "%281%29" in body["href"] or "+%281%29" in body["href"]

    with allure.step("Validate original folder still exists"):
        metadata_response = client.get_resource_metadata(unique_folder_name)
        metadata_body = metadata_response.json()

        assert_status_code(metadata_response, 200)
        assert metadata_body["name"] == unique_folder_name
        assert metadata_body["type"] == "dir"


@allure.feature("Trash lifecycle")
@allure.story("Restore resource from trash")
@allure.title("Should restore folder with overwrite true")
def test_restore_folder_from_trash_with_overwrite_true(
        client,
        unique_folder_name,
        created_folders
):
    with allure.step("Create source folder"):
        create_response = client.create_folder(unique_folder_name)
        assert_status_code(create_response, 201)

    with allure.step("Move source folder to trash"):
        delete_response = client.delete_resource(
            path=unique_folder_name,
            permanently=False
        )
        assert_status_code(delete_response, 204)

    with allure.step("Get real folder path in trash"):
        trash_path = get_trash_path_by_name(client, unique_folder_name)

    with allure.step("Create folder with same name on disk"):
        create_same_name_response = client.create_folder(unique_folder_name)
        assert_status_code(create_same_name_response, 201)

    with allure.step("Restore from trash with overwrite true"):
        restore_response = client.restore_from_trash(
            path=trash_path,
            overwrite=True
        )
        body = restore_response.json()
        created_folders.append(unique_folder_name)

    with allure.step("Validate restore response"):
        assert restore_response.status_code in [201, 202]
        assert_schema(body, LINK_SCHEMA)

    with allure.step("Validate restored folder exists"):
        metadata_response = client.get_resource_metadata(unique_folder_name)
        metadata_body = metadata_response.json()

        assert_status_code(metadata_response, 200)
        assert metadata_body["type"] == "dir"
        assert metadata_body["path"] == f"disk:/{unique_folder_name}"